module CC.CC (Ty : Set) (Var : Ty → Ty → Set) where

-- Reference: I Beylin and P Dybjer (1995)

open import Relation.Binary.Construct.Closure.Equivalence
  using (EqClosure ; symmetric)
  renaming (isEquivalence to EqClosureIsEquivalence)

private
  variable
    a b c : Ty

infixr 4 _∙_

data Tm : (a b : Ty) → Set where
  var   : Var a b → Tm a b
  id    : Tm a a
  _∙_   : Tm b c → Tm a b → Tm a c

infix 3 _≈_ _∼_

private
  variable
    f g h : Tm a b

data _∼_ : Tm a b → Tm a b → Set where
  idl-∼   : id ∙ f ∼ f
  idr-∼   : f ∼ f ∙ id
  assoc-∼ : (f ∙ g) ∙ h ∼ f ∙ (g ∙ h)

_≈_  : Tm a b → Tm a b → Set
_≈_   = EqClosure _∼_

-- Obs: Tm/≈ gives the free category generated by a graph whose nodes
-- are given by `Ty` and edges are given by `Var`

data 𝒩 : (a b : Ty) → Set where
  id    : 𝒩 a a
  _∙_   : Var b c → 𝒩 a b → 𝒩 a c

Tm' : Ty → Ty → Set
Tm' a b  = 𝒩 a b

⟦_⟧→̇⟦_⟧ : Ty → Ty → Set
⟦ a ⟧→̇⟦ b ⟧ = {c : Ty} → (Tm' c a → Tm' c b)

eval : Tm a b → ⟦ a ⟧→̇⟦ b ⟧
eval (var x)    = x ∙_
eval id         = λ z → z
eval (t ∙ u)    = λ x → eval t (eval u x)

rf : 𝒩 a b → Tm a b
rf id      = id
rf (x ∙ t) = var x ∙ rf t

quot : ⟦ a ⟧→̇⟦ b ⟧ → Tm a b
quot f = rf (f id)

norm : Tm a b → Tm a b
norm t = quot (eval t)
